### ISSUE TITLE
when will a "receipt request" 0x0000800000000000 work on german version

### ISSUE THREAD

**Issue by gms-kurt** [fiskaltrust/interface-doc#107]
The receipt request works perfect on austrian version, but not on german version. Will it work in the very near future?

Die Beleganfrage mit ReceiptCase 0x0000800000000000 funktioniert bestens in der österr. Version, aber noch nicht in der deutschen. Gibt es einen Zeitplan, bis wann das programmiert ist oder kommt die Beleganfrage nicht in die deutsche Version?

**Comment by aedler-ft** [comment]
Which version of middleware are you using? there was a know issue which should have been fixed in 1.3.2 https://docs.fiskaltrust.cloud/doc/release-notes/middleware/middleware-1.3.2.html#stability-improvements

**Comment by gms-kurt** [comment]
Thanks for your fast answer. We allready used 1.3.3 and updated now to 1.3.5 but the bug is still there. 
Just for testing I sent the whole JSON without this flag and it worked (as a normal bill with implicity flag).
`"ftReceiptCase":4919338172267102209`  ~ 4445000100000001
But when I add this receipt-request-flag to ftReceiptCase on the same JSON-string, nothing happens. 
There is even no reaction at the service (I started it from commandline, to see your logging).
`"ftReceiptCase":4919478909755457537`  ~ 4445800100000001

**Comment by gms-kurt** [comment]
The error message I get is the following
`Der Server konnte die Anforderung aufgrund eines internen Fehlers nicht verarbeiten. Wenn Sie weitere Informationen zum Fehler erhalten möchten, aktivieren Sie entweder IncludeExceptionDetailInFaults (über das ServiceBehaviorAttribute oder das <serviceDebug>-Konfigurationsverhalten) für den Client, um die Ausnahmeinformationen zurück an den Server zu senden, oder aktivieren Sie die Ablaufverfolgung gemäß der Microsoft .NET Framework SDK-Dokumentation, und überprüfen Sie die Serverablaufverfolgungsprotokolle.`

**Comment by TSchmiedlechner** [comment]
Hi! This functionality should indeed work as expected with versions >1.3.2. Are you setting `cbReceiptReference` in your request? If yes, could you please share the full JSON requests you are using?

Thanks in advance!

**Comment by gms-kurt** [comment]
Hi! A normal Receipt works (with implicity flag):

Request:  {"ftCashBoxID":"608d2d51-fda7-4d96-b2e2-ef2879975bcf","ftPosSystemId":"745be035-a5c0-e511-80ff-3863bb348bb0","cbTerminalID":"832","cbReceiptReference":"55980","cbChargeItems":[{"description":"Prosecco 0,3 auf Eis","ftChargeItemCase":4919338167972134912,"productNumber":"150074","quantity":"1","amount":"6.5","vATRate":"16"}],"cbPayItems":[{"description":"Bar","ftPayItemCase":4919338167972134913,"quantity":"1","amount":"6.5"}],"ftReceiptCase":4919338172267102209,"ftReceiptCaseData":"","cbUser":"","cbArea":"","cbCustomer":"","cbSettlement":"","cbPreviousReceiptReference":"","cbReceiptMoment":"2020-08-25T14:36:32.053+02:00","cbReceiptAmount":"6.5"}

Same JSON with receipt-request-flag:

Request:  {"ftCashBoxID":"608d2d51-fda7-4d96-b2e2-ef2879975bcf","ftPosSystemId":"745be035-a5c0-e511-80ff-3863bb348bb0","cbTerminalID":"832","cbReceiptReference":"55980","cbChargeItems":[{"description":"Prosecco 0,3 auf Eis","ftChargeItemCase":4919338167972134912,"productNumber":"150074","quantity":"1","amount":"6.5","vATRate":"16"}],"cbPayItems":[{"description":"Bar","ftPayItemCase":4919338167972134913,"quantity":"1","amount":"6.5"}],"ftReceiptCase":4919478909755457537,"ftReceiptCaseData":"","cbUser":"","cbArea":"","cbCustomer":"","cbSettlement":"","cbPreviousReceiptReference":"","cbReceiptMoment":"2020-08-25T14:38:54.734+02:00","cbReceiptAmount":"6.5"}

**Comment by gms-kurt** [comment]
Maybe the different receipt moment is a problem... I'll check this.

**Comment by TSchmiedlechner** [comment]
Thanks, I just tried to reproduce this, but it seems to work fine for me with your exact requests. 

Which communication protocol are you using? Could you please enable debug-logs with the additional command line parameter `-verbosity=Debug` and try again?

**Comment by gms-kurt** [comment]
We use SOAP and WSDL. Maybe the WSDL-file is too old:
`// WSDL     : fiskaltrust.interface.1.0.16298.1022-rc.wsdl
// Encoding : utf-8
// Codegen  : [wfUseSettersAndGetters+]
// Version  : 1.0
// (08.06.2018 13:30:31 - - $Rev: 90173 $)
`

**Comment by gms-kurt** [comment]
I had a new idea and it worked: 
when I use $0000100000000000 as receipt-request-flag, it works and sends back the correct JSON response

**Comment by gms-kurt** [comment]
no, that was not the solution. Because it always sends back a JSON response, even if the record does not exist in the database. So with this "modified" receipt-request-flag it is a normal bill, thats the reason for the correct JSON response.

So back to your last answer: with the parameter -verbosity=Debug I see no extra logging...

**Comment by TSchmiedlechner** [comment]
Hi, this is indeed a very weird issue, as I am still not able to reproduce it...sorry for this inconvenience. The WSDL file should be okay, we did not change the SOAP interface.

I asked our PM team to reach out to you about this, maybe the issue can be clarified more easily in a direct way.

**Comment by christian-rogobete** [comment]
Hello @gms-kurt thank you for reporting this issue. I would like to look at the problem with you together directly. Could you please contact me at support-poscreator@fiskaltrust.de so that we can plan a meeting?

**Comment by christian-rogobete** [comment]
Issue found and solved by @gms-kurt: charge item content in request and receipt request were not 100% identical. I will close this issue for now. Thank you for adding it.
